replicaCount: 2

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  name: myapp-service
  type: ClusterIP
  port: 80
  targetPort: 8080

container:
  name: myapp
  port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  path: /
  pathType: Prefix
